# Generated by Django 4.2.4 on 2024-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('course_code', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=30)),
                ('roll', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
